-- Seed gerado a partir de SETOR_MOTIV_REFUGO_E_RECURSO.xlsx

-- Setores
insert into setores (nome) values ('COLADEIRA') on conflict (nome) do nothing;
insert into setores (nome) values ('CORTE') on conflict (nome) do nothing;
insert into setores (nome) values ('EMBALAGEM') on conflict (nome) do nothing;
insert into setores (nome) values ('FURADEIRA') on conflict (nome) do nothing;
insert into setores (nome) values ('LINHA DE PINTURA') on conflict (nome) do nothing;
insert into setores (nome) values ('USINAGEM') on conflict (nome) do nothing;

-- Motivos (catalogo geral, codigo do motivo preservado)
insert into motivos (codigo, descricao) values ('0', 'MOTIVO NÃO IDENTIFICADO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('1', 'CORTE MATERIAL/TROCADO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('2', 'FALHA DO SISTEMA OPERACIONAL/MÁQUINA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('3', 'MARCA DE RISCADOR') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('4', 'PEÇA SECCIONADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('5', 'CANAL FORA DE MEDIDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('6', 'FRESAGEM DE PEÇA INVERTIDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('7', 'GABARITO ERRADO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('8', 'MARCA DE FRESA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('9', 'PEÇA CHANFRADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('10', 'PEÇA COLADA FORA DE MEDIDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('11', 'PEÇA COLADA/ GRAMPEADA FORA DE ESQUADRO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('12', 'PEÇA FRESADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('13', 'BORDA COLADA DO LADO ERRADO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('14', 'BORDA DESCOLANDO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('15', 'DANIFICOU AO COLAR/REFILAR') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('16', 'BROCA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('17', 'FURAÇÃO INVERTIDA PEÇA/ REGULAGEM') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('18', 'FURO DESCENTRALIZADO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('19', 'FURO FORA DE POSIÇÃO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('20', 'PEÇA FURADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('21', 'COR FORA DO PADRÃO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('22', 'PEÇA MAL CALIBRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('23', 'PEÇA PINTADA DO LADO ERRADO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('24', 'EXCESSO LIXAMENTO SUPERFÍCIE') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('25', 'CAIXA ABERTA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('26', 'CAIXA AVARIADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('27', 'FALTA DE PEÇA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('28', 'QUEDA DE CAIXA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('29', 'DANIFICOU AO REGULAR') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('30', 'DANIFICOU NA MÁQUINA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('31', 'DIVERGÊNCIA DE QUANTIDADE (P/+OU-)') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('32', 'DOCUMENTAÇÃO DESATUALIZADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('33', 'ESTRAGOU NO RETRABALHO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('34', 'FALHA NA DOCUMENTAÇÃO/INFORMAÇÃO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('35', 'FALHA NA OPERAÇÃO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('36', 'MATÉRIA PRIMA NÃO CONFORME') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('37', 'PEÇA ENCAVALADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('38', 'PEÇA FORA DE MEDIDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('39', 'PEÇA FORA DE ESQUADRO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('40', 'PEÇA RISCADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('41', 'PEÇA RISCADA/ MANCHADA/  MARCADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('42', 'PEÇA SERRILHADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('43', 'PROGRAMAÇÃO OPERACIONAL NÃO CONFORME') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('44', 'QUEDA DE PEÇA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('45', 'QUEDA DE PILHA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('46', 'REPOSIÇÃO DE PEÇA P/ PREMIAÇÃO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('47', 'REGULAGEM ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('48', 'REFUGO TERCEIROS') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('50', 'PEÇA DERRUBADA - DESABILITADO - NÃO PERMITIU EXCLUIR NA PPI') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('52', 'REFUGO PADRÃO - DESABILITADO - NÃO PERMITIU EXCLUIR NA PPI') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('53', 'PEÇA SUMIU NO PROCESSO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('54', 'QUEBRA VIDRO/ESPELHO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('55', 'DEFEITO VIDRO/ESPELHO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('56', 'BORDA QUEBRANDO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('57', 'FURAÇÃO FUNDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('58', 'GRAMPO ESTOROU') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('59', 'GRAMPO RISCANDO A PEÇA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('60', 'PEÇA SARRAFEADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('61', 'PEÇA MOLHADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('62', 'PEÇA EFEITO BANANA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('63', 'PEÇA TERC REFUGADA NO PROCESSO') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('64', 'FURAÇÃO VAZADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('65', 'FALHA NO SENSOR') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('66', 'QUEDA DE ENERGIA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('67', 'PEÇA BATIDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('68', 'PEÇA TRINCADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('69', 'FALTA DE AR') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('70', 'TAMPO DANIFICADO AO RETIRAR APLIQUE') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('71', 'DEFEITO NA CHAPA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('72', 'PEÇA DANIFIFICADA (EMPILHADEIRA)') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('73', 'ESTRAGOU NA PRÉ MONTAGEM') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('74', 'PEÇA MONTADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('75', 'PEÇA CORTADA ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('76', 'FALTOU COLAR A BORDA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('77', 'BORDA COLADO DA COR ERRADA') on conflict (codigo) do nothing;
insert into motivos (codigo, descricao) values ('99', 'REAPROVEITAMENTO DE PEÇA') on conflict (codigo) do nothing;

-- Maquinas (uma por setor)
insert into maquinas (codigo, nome, setor_id) select '1101', 'ESQUAD', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1102', 'ESQUAD', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1103', 'SEC. GIBEN', id from setores where nome = 'CORTE' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1104', 'ESQUAD', id from setores where nome = 'CORTE' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1105', 'TUPIA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1106', 'SERRA FITA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1107', 'MULTI-SERRA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1108', 'TUPIA SUP', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1109', 'MAQ GRAMPO', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1110', 'SEC.GIBEN', id from setores where nome = 'CORTE' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1111', 'GRAMPO PORTA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1112', 'GRAMPO PORTA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1113', 'GRAMPO TAMPO', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1114', 'SEC .HOMAG', id from setores where nome = 'CORTE' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1115', 'ESQUAD', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1201', 'FRESA FC160E', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1202', 'FRESA DALMAQ', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1203', 'FRESA DALMAQ', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1204', 'TUPIA FRESA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1205', 'TRABALHO MAN', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1301', 'COL NAN AUT', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1302', 'COL MAC CBN', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1303', 'COL MAC CBN', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1304', 'CB. MANUAL', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1305', 'COL MAC SINGL', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1306', 'COL MAC', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1307', 'COL NAN AUT', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1308', 'REFIL. MANUAL', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1309', 'COL HOMAG', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1310', 'COL ESQUAD', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1311', 'CB CURVA', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1312', 'DESTOPAR MANU', id from setores where nome = 'USINAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1313', 'COL NAN 45''', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1314', 'COL NAN 45''', id from setores where nome = 'COLADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1401', 'FUR BANC', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1402', 'FUR LIDEAR', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1404', 'FUR INVICTA', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1407', 'FUR DRILL', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1408', 'FUR MAC RAPID', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1409', 'FUR BIESSE', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1411', 'FUR BIESSE', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1415', 'FUR LIDEAR', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1416', 'FUR BHX', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '1417', 'CENTRO FUR', id from setores where nome = 'FURADEIRA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '3101', 'LINHA PINT 01', id from setores where nome = 'LINHA DE PINTURA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '3102', 'LINHA PINT 02', id from setores where nome = 'LINHA DE PINTURA' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '4101', 'LINHA EMB 01', id from setores where nome = 'EMBALAGEM' on conflict (codigo, nome) do nothing;
insert into maquinas (codigo, nome, setor_id) select '4102', 'LINHA EMB 02', id from setores where nome = 'EMBALAGEM' on conflict (codigo, nome) do nothing;

-- Relacao motivo <-> setor (quais motivos aparecem em quais setores)
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '0' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '0' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '0' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '0' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '0' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '0' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '1' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '10' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '11' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '12' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '13' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '14' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '15' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '16' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '17' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '18' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '19' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '2' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '20' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '21' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '22' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '23' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '24' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '25' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '26' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '27' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '28' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '29' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '29' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '29' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '29' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '29' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '29' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '3' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '30' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '30' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '30' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '30' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '30' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '30' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '31' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '31' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '31' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '31' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '31' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '31' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '32' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '32' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '32' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '32' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '32' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '32' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '33' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '33' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '33' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '33' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '33' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '33' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '34' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '34' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '34' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '34' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '34' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '34' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '35' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '35' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '35' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '35' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '35' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '35' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '36' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '36' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '36' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '36' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '36' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '36' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '37' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '37' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '37' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '37' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '37' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '37' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '38' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '38' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '38' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '38' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '38' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '38' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '39' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '39' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '39' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '39' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '39' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '39' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '4' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '40' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '40' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '40' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '40' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '40' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '40' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '41' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '41' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '41' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '41' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '41' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '41' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '42' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '42' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '42' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '42' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '42' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '42' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '43' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '43' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '43' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '43' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '43' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '43' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '44' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '44' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '44' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '44' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '44' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '44' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '45' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '45' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '45' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '45' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '45' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '45' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '46' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '46' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '46' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '46' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '46' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '46' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '47' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '47' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '47' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '47' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '47' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '47' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '48' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '48' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '48' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '48' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '48' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '48' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '5' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '50' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '50' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '50' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '50' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '50' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '50' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '52' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '52' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '52' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '52' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '52' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '52' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '53' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '53' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '53' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '53' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '53' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '53' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '54' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '54' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '54' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '54' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '54' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '54' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '55' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '55' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '55' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '55' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '55' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '55' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '56' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '56' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '56' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '56' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '56' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '56' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '57' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '58' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '59' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '6' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '60' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '61' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '61' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '61' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '61' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '61' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '61' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '62' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '62' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '62' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '62' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '62' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '62' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '63' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '63' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '63' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '63' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '63' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '63' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '64' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '65' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '65' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '65' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '65' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '65' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '65' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '66' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '66' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '66' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '66' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '66' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '66' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '67' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '67' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '67' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '67' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '67' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '67' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '68' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '68' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '68' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '68' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '68' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '68' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '69' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '69' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '69' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '69' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '69' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '69' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '7' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '70' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '70' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '70' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '70' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '70' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '70' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '71' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '71' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '71' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '71' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '71' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '71' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '72' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '72' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '72' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '72' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '72' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '72' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '73' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '73' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '73' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '73' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '73' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '73' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '74' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '74' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '74' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '74' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '74' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '74' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '75' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '76' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '77' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '8' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '9' and s.nome = 'USINAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '99' and s.nome = 'COLADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '99' and s.nome = 'CORTE' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '99' and s.nome = 'EMBALAGEM' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '99' and s.nome = 'FURADEIRA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '99' and s.nome = 'LINHA DE PINTURA' on conflict do nothing;
insert into motivo_setor (motivo_id, setor_id) select m.id, s.id from motivos m, setores s where m.codigo = '99' and s.nome = 'USINAGEM' on conflict do nothing;
